/** Default program catalog — seeded when the programs table is empty. */
export const PROGRAMS_SEED = [
  {
    title: 'Traditional Arts & Crafts',
    category: 'Arts Education',
    section: 'catalog',
    description:
      'Master Adinkra, Kente, pottery, and wood carving with master artisans in Accra and Kumasi.',
    duration: '8 weeks',
    level: 'All levels welcome',
    iconKey: 'Palette',
    sortOrder: 0,
    features: ['Hands-on workshops', 'Master artisan guidance', 'Cultural context', 'Materials provided'],
  },
  {
    title: 'African Music & Rhythm',
    category: 'Cultural Workshops',
    section: 'catalog',
    description:
      'Explore drumming, vocal traditions, and instruments through community-centered music education.',
    duration: '12 weeks',
    level: 'Beginner to advanced',
    iconKey: 'Music',
    sortOrder: 1,
    features: ['Drum circles', 'Instrument making', 'Performance opportunities', 'Music theory'],
  },
  {
    title: 'Storytelling & Oral Traditions',
    category: 'Cultural Workshops',
    section: 'catalog',
    description:
      'Learn Ananse tales, griot traditions, and the power of oral history in community settings.',
    duration: '6 weeks',
    level: 'All levels welcome',
    iconKey: 'BookOpen',
    sortOrder: 2,
    features: ['Story circles', 'Performance training', 'Cultural narratives', 'Community sharing'],
  },
  {
    title: 'Contemporary African Art',
    category: 'Arts Education',
    section: 'catalog',
    description:
      'Blend traditional techniques with modern expression in painting, sculpture, and mixed media.',
    duration: '10 weeks',
    level: 'Intermediate to advanced',
    iconKey: 'Brush',
    sortOrder: 3,
    features: ['Studio time', 'Artist mentorship', 'Exhibition opportunities', 'Portfolio development'],
  },
  {
    title: 'Dance & Movement',
    category: 'Cultural Workshops',
    section: 'catalog',
    description:
      'Ceremonial and contemporary African dance — energy, grace, and cultural context for all bodies.',
    duration: '8 weeks',
    level: 'All fitness levels',
    iconKey: 'Drama',
    sortOrder: 4,
    features: ['Daily movement', 'Cultural context', 'Performance preparation', 'Community building'],
  },
  {
    title: 'Cultural Leadership Training',
    category: 'Community Training',
    section: 'catalog',
    description:
      'Become a cultural ambassador and community leader in arts and heritage preservation.',
    duration: '16 weeks',
    level: 'Advanced',
    iconKey: 'Award',
    sortOrder: 5,
    features: ['Leadership workshops', 'Community projects', 'Mentorship program', 'Certification'],
  },
  {
    title: 'Sankofa Mentorship',
    category: 'Sankofa',
    section: 'sankofa',
    description: 'Emerging leaders paired with mentors for culturally grounded leadership.',
    duration: '',
    level: '',
    iconKey: 'UserCircle',
    sortOrder: 0,
    features: [],
  },
  {
    title: 'Sankofa Mediation',
    category: 'Sankofa',
    section: 'sankofa',
    description: 'Conflict resolution blending tradition and modern practice.',
    duration: '',
    level: '',
    iconKey: 'Bird',
    sortOrder: 1,
    features: [],
  },
  {
    title: 'Sankofa Resources',
    category: 'Sankofa',
    section: 'sankofa',
    description: 'African-centered education, research, and learning archives.',
    duration: '',
    level: '',
    iconKey: 'BookOpen',
    sortOrder: 2,
    features: [],
  },
  {
    title: 'Sankofa Music',
    category: 'Sankofa',
    section: 'sankofa',
    description: 'Community building through music, rhythm, and shared celebration.',
    duration: '',
    level: '',
    iconKey: 'Music',
    sortOrder: 3,
    features: [],
  },
  {
    title: 'Sankofa Kitchen & Health',
    category: 'Sankofa',
    section: 'sankofa',
    description: 'Nutrition and wellness workshops grounded in NEWSTART principles.',
    duration: '',
    level: '',
    iconKey: 'Salad',
    sortOrder: 4,
    features: [],
  },
  {
    title: 'Sankofa Sabbath & Volunteering',
    category: 'Sankofa',
    section: 'sankofa',
    description: 'Rest, renewal, and service-learning for purposeful living.',
    duration: '',
    level: '',
    iconKey: 'Sun',
    sortOrder: 5,
    features: [],
  },
] as const
